### ISSUE TITLE
Is it necessary to specify a specific version of Elixir for this project?

### ISSUE THREAD

**Issue by kenshinji** [AgileVentures/Paironauts#19]
In `mix.exs`, there is a line ` elixir: "1.6.3"` specifying the Elixir version. It stops me from running it either on a version lower or higher than this. 

> ** (Mix) You're trying to run :paironauts on Elixir v1.6.4 but it has declared in its mix.exs file it supports only Elixir 1.6.3
> ** (Mix) You're trying to run :paironauts on Elixir v1.6.1 but it has declared in its mix.exs file it supports only Elixir 1.6.3

**Comment by SherSpock** [comment]
@kenshinji Please feel free to switch it to ~>1.6 or equivalent. We were trying to pin everything to resolve some issues with the test suite on certain boxes

@tansaku @bcb37 @praveendhawan Please chime in if that seems counterproductive

**Comment by SherSpock** [comment]
OK the longer I think about this, the more I want to keep the Elixir version pinned. Initially I thought, "yeah, let's fuzz it" to unblock new contributors, but I think pinning it was actually the right call. It seems to me that it would make more sense to document our project's supported approach to Elixir version management than to roll the change back.

Fundamentally, I feel locking our dependencies down removes a big chunk of guesswork from dependency management and protects us from projects that might not do the greatest job of following SemVer. Pinning the Ruby version is also a pretty common practice in our sister ecosystem.

The only way I see a drawback in pinning the Elixir version is if we don't add documentation about how contributors ought to handle this piece of project dependency setup.

**Comment by SherSpock** [comment]
Closed by #17. Recommend we circle back later to pin the Elixir version and add version management setup to the docs. There is an open issue for this, #20.
